#! /bin/sh

pgrep -x sxhkd &>/dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config pointer_modifier mod1

bspc config border_width     1
bspc config window_gap      12
bspc config top_padding     28
bspc config bottom_padding   0
bspc config left_padding     0
bspc config right_padding    0
bspc config split_ratio      0.50

bspc config single_monocle          true
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config paddingless_monocle     false
bspc config top_monocle_padding     12
bspc config bottom_monocle_padding  12
bspc config left_monocle_padding    12
bspc config right_monocle_padding   12

bspc config focus_follows_pointer  true
bspc config click_to_focus         any

bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true

bspc config mapping_events_count  -1

bspc config normal_border_color    #000000
bspc config active_border_color    #444444
bspc config focused_border_color   #ffffff
bspc config presel_feedback_color  #cc0000

d.compositor &
d.wallpaper &
d.panel &
d.terminal_emulator &
