#! /bin/sh

pgrep -x sxhkd &>/dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config pointer_modifier mod1

bspc config border_width     1
bspc config window_gap      12
bspc config top_padding     28
bspc config bottom_padding  28
bspc config left_padding     0
bspc config right_padding    0
bspc config split_ratio      0.50

bspc config single_monocle          true
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config paddingless_monocle     false
bspc config top_monocle_padding     0
bspc config bottom_monocle_padding  0
bspc config left_monocle_padding    0
bspc config right_monocle_padding   0

bspc config focus_follows_pointer  true
bspc config click_to_focus         any

bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true

bspc config mapping_events_count  -1

bspc config normal_color_border   #000000
bspc config active_border_color   #444444
bspc config focused_border_colo r #ffffff
bspc config presel_feedback_color #cc0000

for i in /usr/share/fonts/*
do xset +fp $i
done

xset fp rehash
fc-cache -fv

xset b off
xset c on
xset +dpms
xset k
xset led on
xset r on

xsetroot -cursor_name left_ptr &
xrdb merge .Xresources &
xfsettingsd &
setxkbmap -option grp:alt_shift_toggle us,ru &
nitrogen --restore --set-zoom-fill &
d.panel &
exec d.terminal_emulator
